### ISSUE TITLE
邮件详情无法看html里面的附件图片

### ISSUE THREAD

**Issue by Ryan0520** [lxypeter/CYMailDemo#1]
如题，如果邮件内容很大的时候，webView没有缩放，这点体验不太好。。

**Comment by lxypeter** [comment]
@Ryan0520 谢谢你的反馈，针对webView缩放已经优化

**Comment by Ryan0520** [comment]
博主，请教一个问题，现在demo里是没有做邮件同步的，假如需要做邮件同步的话，有几种做法呢？

**Comment by lxypeter** [comment]
@Ryan0520 邮件同步指的是自动更新？

**Comment by Ryan0520** [comment]
@lxypeter 就是已经以前已经加载过的邮件，会更新状态，例如总共100封邮件， 你已经加载了100封，这个时候，你在网页客户端删除了一些邮件，标星了一些邮件，然后你在手机客户端里下拉刷新，同步这些邮件的状态这种机制~

**Comment by lxypeter** [comment]
@Ryan0520 感觉这个不太好实现？现在因为尽量避免过多调用接口耗费流量和时间，所以加载之后全部都是进行了缓存操作。哪怕单纯是刷新邮件相关的状态的话也还是需要对邮件都进行重新加载。如果这种动态更新需求比较大的话，可能需要从最早的一封缓存邮件ID开始，至最新的邮件ID进行重新加载。只从现今mailcore2提供的API来看，暂时没有想到更好的办法。

**Comment by Ryan0520** [comment]
所以这个是重点需要突破的地方啊，就类似微博他们那种机制，可能内部定制了一个好的同步机制。最近在想有没有好的解决方案对于这种需要分页加载，并且需要同步类型的机制。

**Comment by lxypeter** [comment]
@Ryan0520 我去看了一下mailcore2的API，在MCOIMAPSession类中提供了这个方法`syncMessagesWithFolder:requestKind:uids:modSeq:`，可以根据uid的范围获取邮件的最新状态，对于已经删除的邮件就不在返回列表。邮件对象中不可变的部分例如标题收件人等应该没有查询，因为取值为nil。这样可以保证尽可能少地耗费流量和提高查询速度。根据这一点，可以在下拉刷新时使用缓存的首个邮件的uid调用接口进行查询，通过对比uid，对邮件缓存进行更新和删除，因为uid都是有序的，应该比较方便操作。这算是一个思路吧。
